version: '2.4'
services:
  publisher:
    image: job-queue:local
    command: ./publisher
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - MQ_HOST=queue
      - QUEUE_NAME=add_q
  listener:
    image: job-queue:local
    command: ./listener
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - MQ_HOST=queue
      - QUEUE_NAME=add_q
  queue:
    image: rabbitmq:3.7-alpine
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "node_health_check"]
      timeout: 5s
      interval: 5s
      retries: 5
    expose:
      - "5672"